"""auto-vote

Revision ID: 1dafe4f1829e
Revises: 23028553a98a
Create Date: 2024-09-14 16:25:25.933906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dafe4f1829e'
down_revision: Union[str, None] = '23028553a98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.drop_table('basket_b')
    op.drop_table('employees')
    op.drop_table('basket_a')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket_a',
    sa.Column('a', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fruit_a', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('a', name='basket_a_pkey')
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('basket_b',
    sa.Column('b', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fruit_b', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('b', name='basket_b_pkey')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
